// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBedhjcIu7M8fPyV2hFo_G3a8SROLPYWX8',
    appId: '1:890130131144:web:2261d75f55030694e75dfd',
    messagingSenderId: '890130131144',
    projectId: 'flutterauth-bdd76',
    authDomain: 'flutterauth-bdd76.firebaseapp.com',
    storageBucket: 'flutterauth-bdd76.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUPB_h24G44VCoSaNGsiJusklvlqrk7m8',
    appId: '1:890130131144:android:b6ea2b10a207f12be75dfd',
    messagingSenderId: '890130131144',
    projectId: 'flutterauth-bdd76',
    storageBucket: 'flutterauth-bdd76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABXyFebwLt1x5G-1HdlQWkINad5GM2SUs',
    appId: '1:890130131144:ios:52176dad7e1b0008e75dfd',
    messagingSenderId: '890130131144',
    projectId: 'flutterauth-bdd76',
    storageBucket: 'flutterauth-bdd76.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABXyFebwLt1x5G-1HdlQWkINad5GM2SUs',
    appId: '1:890130131144:ios:277c2b3264ac9dffe75dfd',
    messagingSenderId: '890130131144',
    projectId: 'flutterauth-bdd76',
    storageBucket: 'flutterauth-bdd76.appspot.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
